// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version:
// source: opentelemetry/proto/profiles/v1experimental/pprofextended.proto

package opentelemetry_proto_profiles_v1experimental

import (
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	v1 "go.opentelemetry.io/proto/lite/otlp/common/v1"
	strconv "strconv"
)

// Copyright 2023, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file includes work covered by the following copyright and permission notices:
//
// Copyright 2016 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Profile is a common stacktrace profile format.
//
// Measurements represented with this format should follow the
// following conventions:
//
// - Consumers should treat unset optional fields as if they had been
//   set with their default value.
//
// - When possible, measurements should be stored in "unsampled" form
//   that is most useful to humans.  There should be enough
//   information present to determine the original sampled values.
//
// - On-disk, the serialized proto must be gzip-compressed.
//
// - The profile is represented as a set of samples, where each sample
//   references a sequence of locations, and where each location belongs
//   to a mapping.
// - There is a N->1 relationship from sample.location_id entries to
//   locations. For every sample.location_id entry there must be a
//   unique Location with that index.
// - There is an optional N->1 relationship from locations to
//   mappings. For every nonzero Location.mapping_id there must be a
//   unique Mapping with that index.

// Specifies the method of aggregating metric values, either DELTA (change since last report)
// or CUMULATIVE (total since a fixed start time).
type AggregationTemporality int32

const (
	// UNSPECIFIED is the default AggregationTemporality, it MUST not be used.
	AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED AggregationTemporality = 0
	// * DELTA is an AggregationTemporality for a profiler which reports
	// changes since last report time. Successive metrics contain aggregation of
	// values from continuous and non-overlapping intervals.
	//
	// The values for a DELTA metric are based only on the time interval
	// associated with one measurement cycle. There is no dependency on
	// previous measurements like is the case for CUMULATIVE metrics.
	//
	// For example, consider a system measuring the number of requests that
	// it receives and reports the sum of these requests every second as a
	// DELTA metric:
	//
	// 1. The system starts receiving at time=t_0.
	// 2. A request is received, the system measures 1 request.
	// 3. A request is received, the system measures 1 request.
	// 4. A request is received, the system measures 1 request.
	// 5. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0 to
	// t_0+1 with a value of 3.
	// 6. A request is received, the system measures 1 request.
	// 7. A request is received, the system measures 1 request.
	// 8. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0+1 to
	// t_0+2 with a value of 2.
	AggregationTemporality_AGGREGATION_TEMPORALITY_DELTA AggregationTemporality = 1
	// * CUMULATIVE is an AggregationTemporality for a profiler which
	// reports changes since a fixed start time. This means that current values
	// of a CUMULATIVE metric depend on all previous measurements since the
	// start time. Because of this, the sender is required to retain this state
	// in some form. If this state is lost or invalidated, the CUMULATIVE metric
	// values MUST be reset and a new fixed start time following the last
	// reported measurement time sent MUST be used.
	//
	// For example, consider a system measuring the number of requests that
	// it receives and reports the sum of these requests every second as a
	// CUMULATIVE metric:
	//
	// 1. The system starts receiving at time=t_0.
	// 2. A request is received, the system measures 1 request.
	// 3. A request is received, the system measures 1 request.
	// 4. A request is received, the system measures 1 request.
	// 5. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0 to
	// t_0+1 with a value of 3.
	// 6. A request is received, the system measures 1 request.
	// 7. A request is received, the system measures 1 request.
	// 8. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0 to
	// t_0+2 with a value of 5.
	// 9. The system experiences a fault and loses state.
	// 10. The system recovers and resumes receiving at time=t_1.
	// 11. A request is received, the system measures 1 request.
	// 12. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_1 to
	// t_0+1 with a value of 1.
	//
	// Note: Even though, when reporting changes since last report time, using
	// CUMULATIVE is valid, it is not recommended.
	AggregationTemporality_AGGREGATION_TEMPORALITY_CUMULATIVE AggregationTemporality = 2
)

// Enum value maps for AggregationTemporality.
var (
	AggregationTemporality_name = map[int32]string{
		0: "AGGREGATION_TEMPORALITY_UNSPECIFIED",
		1: "AGGREGATION_TEMPORALITY_DELTA",
		2: "AGGREGATION_TEMPORALITY_CUMULATIVE",
	}
	AggregationTemporality_value = map[string]int32{
		"AGGREGATION_TEMPORALITY_UNSPECIFIED": 0,
		"AGGREGATION_TEMPORALITY_DELTA":       1,
		"AGGREGATION_TEMPORALITY_CUMULATIVE":  2,
	}
)

func (x AggregationTemporality) Enum() *AggregationTemporality {
	p := new(AggregationTemporality)
	*p = x
	return p
}

func (x AggregationTemporality) String() string {
	name, valid := AggregationTemporality_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Indicates the semantics of the build_id field.
type BuildIdKind int32

const (
	// Linker-generated build ID, stored in the ELF binary notes.
	BuildIdKind_BUILD_ID_LINKER BuildIdKind = 0
	// Build ID based on the content hash of the binary. Currently no particular
	// hashing approach is standardized, so a given producer needs to define it
	// themselves and thus unlike BUILD_ID_LINKER this kind of hash is producer-specific.
	// We may choose to provide a standardized stable hash recommendation later.
	BuildIdKind_BUILD_ID_BINARY_HASH BuildIdKind = 1
)

// Enum value maps for BuildIdKind.
var (
	BuildIdKind_name = map[int32]string{
		0: "BUILD_ID_LINKER",
		1: "BUILD_ID_BINARY_HASH",
	}
	BuildIdKind_value = map[string]int32{
		"BUILD_ID_LINKER":      0,
		"BUILD_ID_BINARY_HASH": 1,
	}
)

func (x BuildIdKind) Enum() *BuildIdKind {
	p := new(BuildIdKind)
	*p = x
	return p
}

func (x BuildIdKind) String() string {
	name, valid := BuildIdKind_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// Represents a complete profile, including sample types, samples,
// mappings to binaries, locations, functions, string table, and additional metadata.
type Profile struct {
	unknownFields []byte
	// A description of the samples associated with each Sample.value.
	// For a cpu profile this might be:
	//
	//	[["cpu","nanoseconds"]] or [["wall","seconds"]] or [["syscall","count"]]
	//
	// For a heap profile, this might be:
	//
	//	[["allocations","count"], ["space","bytes"]],
	//
	// If one of the values represents the number of events represented
	// by the sample, by convention it should be at index 0 and use
	// sample_type.unit == "count".
	SampleType []*ValueType `protobuf:"bytes,1,rep,name=sample_type,json=sampleType,proto3" json:"sampleType,omitempty"`
	// The set of samples recorded in this profile.
	Sample []*Sample `protobuf:"bytes,2,rep,name=sample,proto3" json:"sample,omitempty"`
	// Mapping from address ranges to the image/binary/library mapped
	// into that address range.  mapping[0] will be the main binary.
	Mapping []*Mapping `protobuf:"bytes,3,rep,name=mapping,proto3" json:"mapping,omitempty"`
	// Locations referenced by samples via location_indices.
	Location []*Location `protobuf:"bytes,4,rep,name=location,proto3" json:"location,omitempty"`
	// Array of locations referenced by samples.
	LocationIndices []int64 `protobuf:"varint,15,rep,packed,name=location_indices,json=locationIndices,proto3" json:"locationIndices,omitempty"`
	// Functions referenced by locations.
	Function []*Function `protobuf:"bytes,5,rep,name=function,proto3" json:"function,omitempty"`
	// Lookup table for attributes.
	AttributeTable []*v1.KeyValue `protobuf:"bytes,16,rep,name=attribute_table,json=attributeTable,proto3" json:"attributeTable,omitempty"`
	// Represents a mapping between Attribute Keys and Units.
	AttributeUnits []*AttributeUnit `protobuf:"bytes,17,rep,name=attribute_units,json=attributeUnits,proto3" json:"attributeUnits,omitempty"`
	// Lookup table for links.
	LinkTable []*Link `protobuf:"bytes,18,rep,name=link_table,json=linkTable,proto3" json:"linkTable,omitempty"`
	// A common table for strings referenced by various messages.
	// string_table[0] must always be "".
	StringTable []string `protobuf:"bytes,6,rep,name=string_table,json=stringTable,proto3" json:"stringTable,omitempty"`
	// frames with Function.function_name fully matching the following
	// regexp will be dropped from the samples, along with their successors.
	DropFrames int64 `protobuf:"varint,7,opt,name=drop_frames,json=dropFrames,proto3" json:"dropFrames,omitempty"` // Index into string table.
	// frames with Function.function_name fully matching the following
	// regexp will be kept, even if it matches drop_frames.
	KeepFrames int64 `protobuf:"varint,8,opt,name=keep_frames,json=keepFrames,proto3" json:"keepFrames,omitempty"` // Index into string table.
	// Time of collection (UTC) represented as nanoseconds past the epoch.
	TimeNanos int64 `protobuf:"varint,9,opt,name=time_nanos,json=timeNanos,proto3" json:"timeNanos,omitempty"`
	// Duration of the profile, if a duration makes sense.
	DurationNanos int64 `protobuf:"varint,10,opt,name=duration_nanos,json=durationNanos,proto3" json:"durationNanos,omitempty"`
	// The kind of events between sampled occurrences.
	// e.g [ "cpu","cycles" ] or [ "heap","bytes" ]
	PeriodType *ValueType `protobuf:"bytes,11,opt,name=period_type,json=periodType,proto3" json:"periodType,omitempty"`
	// The number of events between sampled occurrences.
	Period int64 `protobuf:"varint,12,opt,name=period,proto3" json:"period,omitempty"`
	// Free-form text associated with the profile. The text is displayed as is
	// to the user by the tools that read profiles (e.g. by pprof). This field
	// should not be used to store any machine-readable information, it is only
	// for human-friendly content. The profile must stay functional if this field
	// is cleaned.
	Comment []int64 `protobuf:"varint,13,rep,packed,name=comment,proto3" json:"comment,omitempty"` // Indices into string table.
	// Index into the string table of the type of the preferred sample
	// value. If unset, clients should default to the last sample value.
	DefaultSampleType int64 `protobuf:"varint,14,opt,name=default_sample_type,json=defaultSampleType,proto3" json:"defaultSampleType,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
}

func (*Profile) ProtoMessage() {}

func (x *Profile) GetSampleType() []*ValueType {
	if x != nil {
		return x.SampleType
	}
	return nil
}

func (x *Profile) GetSample() []*Sample {
	if x != nil {
		return x.Sample
	}
	return nil
}

func (x *Profile) GetMapping() []*Mapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *Profile) GetLocation() []*Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Profile) GetLocationIndices() []int64 {
	if x != nil {
		return x.LocationIndices
	}
	return nil
}

func (x *Profile) GetFunction() []*Function {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Profile) GetAttributeTable() []*v1.KeyValue {
	if x != nil {
		return x.AttributeTable
	}
	return nil
}

func (x *Profile) GetAttributeUnits() []*AttributeUnit {
	if x != nil {
		return x.AttributeUnits
	}
	return nil
}

func (x *Profile) GetLinkTable() []*Link {
	if x != nil {
		return x.LinkTable
	}
	return nil
}

func (x *Profile) GetStringTable() []string {
	if x != nil {
		return x.StringTable
	}
	return nil
}

func (x *Profile) GetDropFrames() int64 {
	if x != nil {
		return x.DropFrames
	}
	return 0
}

func (x *Profile) GetKeepFrames() int64 {
	if x != nil {
		return x.KeepFrames
	}
	return 0
}

func (x *Profile) GetTimeNanos() int64 {
	if x != nil {
		return x.TimeNanos
	}
	return 0
}

func (x *Profile) GetDurationNanos() int64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

func (x *Profile) GetPeriodType() *ValueType {
	if x != nil {
		return x.PeriodType
	}
	return nil
}

func (x *Profile) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Profile) GetComment() []int64 {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *Profile) GetDefaultSampleType() int64 {
	if x != nil {
		return x.DefaultSampleType
	}
	return 0
}

// Represents a mapping between Attribute Keys and Units.
type AttributeUnit struct {
	unknownFields []byte
	// Index into string table.
	AttributeKey int64 `protobuf:"varint,1,opt,name=attribute_key,json=attributeKey,proto3" json:"attributeKey,omitempty"`
	// Index into string table.
	Unit int64 `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *AttributeUnit) Reset() {
	*x = AttributeUnit{}
}

func (*AttributeUnit) ProtoMessage() {}

func (x *AttributeUnit) GetAttributeKey() int64 {
	if x != nil {
		return x.AttributeKey
	}
	return 0
}

func (x *AttributeUnit) GetUnit() int64 {
	if x != nil {
		return x.Unit
	}
	return 0
}

// A pointer from a profile Sample to a trace Span.
// Connects a profile sample to a trace span, identified by unique trace and span IDs.
type Link struct {
	unknownFields []byte
	// A unique identifier of a trace that this linked span is part of. The ID is a
	// 16-byte array.
	TraceId []byte `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"traceId,omitempty"`
	// A unique identifier for the linked span. The ID is an 8-byte array.
	SpanId []byte `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"spanId,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
}

func (*Link) ProtoMessage() {}

func (x *Link) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Link) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

// ValueType describes the type and units of a value, with an optional aggregation temporality.
type ValueType struct {
	unknownFields          []byte
	Type                   int64                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // Index into string table.
	Unit                   int64                  `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"` // Index into string table.
	AggregationTemporality AggregationTemporality `protobuf:"varint,3,opt,name=aggregation_temporality,json=aggregationTemporality,proto3" json:"aggregationTemporality,omitempty"`
}

func (x *ValueType) Reset() {
	*x = ValueType{}
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ValueType) GetUnit() int64 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *ValueType) GetAggregationTemporality() AggregationTemporality {
	if x != nil {
		return x.AggregationTemporality
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

// Each Sample records values encountered in some program
// context. The program context is typically a stack trace, perhaps
// augmented with auxiliary information like the thread-id, some
// indicator of a higher level request being handled etc.
type Sample struct {
	unknownFields []byte
	// The indices recorded here correspond to locations in Profile.location.
	// The leaf is at location_index[0]. [deprecated, superseded by locations_start_index / locations_length]
	LocationIndex []uint64 `protobuf:"varint,1,rep,packed,name=location_index,json=locationIndex,proto3" json:"locationIndex,omitempty"`
	// locations_start_index along with locations_length refers to to a slice of locations in Profile.location.
	// Supersedes location_index.
	LocationsStartIndex uint64 `protobuf:"varint,7,opt,name=locations_start_index,json=locationsStartIndex,proto3" json:"locationsStartIndex,omitempty"`
	// locations_length along with locations_start_index refers to a slice of locations in Profile.location.
	// Supersedes location_index.
	LocationsLength uint64 `protobuf:"varint,8,opt,name=locations_length,json=locationsLength,proto3" json:"locationsLength,omitempty"`
	// A 128bit id that uniquely identifies this stacktrace, globally. Index into string table. [optional]
	StacktraceIdIndex uint32 `protobuf:"varint,9,opt,name=stacktrace_id_index,json=stacktraceIdIndex,proto3" json:"stacktraceIdIndex,omitempty"`
	// The type and unit of each value is defined by the corresponding
	// entry in Profile.sample_type. All samples must have the same
	// number of values, the same as the length of Profile.sample_type.
	// When aggregating multiple samples into a single sample, the
	// result has a list of values that is the element-wise sum of the
	// lists of the originals.
	Value []int64 `protobuf:"varint,2,rep,packed,name=value,proto3" json:"value,omitempty"`
	// label includes additional context for this sample. It can include
	// things like a thread id, allocation size, etc.
	//
	// NOTE: While possible, having multiple values for the same label key is
	// strongly discouraged and should never be used. Most tools (e.g. pprof) do
	// not have good (or any) support for multi-value labels. And an even more
	// discouraged case is having a string label and a numeric label of the same
	// name on a sample.  Again, possible to express, but should not be used.
	// [deprecated, superseded by attributes]
	Label []*Label `protobuf:"bytes,3,rep,name=label,proto3" json:"label,omitempty"`
	// References to attributes in Profile.attribute_table. [optional]
	Attributes []uint64 `protobuf:"varint,10,rep,packed,name=attributes,proto3" json:"attributes,omitempty"`
	// Reference to link in Profile.link_table. [optional]
	Link uint64 `protobuf:"varint,12,opt,name=link,proto3" json:"link,omitempty"`
	// Timestamps associated with Sample represented in nanoseconds. These timestamps are expected
	// to fall within the Profile's time range. [optional]
	TimestampsUnixNano []uint64 `protobuf:"varint,13,rep,packed,name=timestamps_unix_nano,json=timestampsUnixNano,proto3" json:"timestampsUnixNano,omitempty"`
}

func (x *Sample) Reset() {
	*x = Sample{}
}

func (*Sample) ProtoMessage() {}

func (x *Sample) GetLocationIndex() []uint64 {
	if x != nil {
		return x.LocationIndex
	}
	return nil
}

func (x *Sample) GetLocationsStartIndex() uint64 {
	if x != nil {
		return x.LocationsStartIndex
	}
	return 0
}

func (x *Sample) GetLocationsLength() uint64 {
	if x != nil {
		return x.LocationsLength
	}
	return 0
}

func (x *Sample) GetStacktraceIdIndex() uint32 {
	if x != nil {
		return x.StacktraceIdIndex
	}
	return 0
}

func (x *Sample) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Sample) GetLabel() []*Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Sample) GetAttributes() []uint64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Sample) GetLink() uint64 {
	if x != nil {
		return x.Link
	}
	return 0
}

func (x *Sample) GetTimestampsUnixNano() []uint64 {
	if x != nil {
		return x.TimestampsUnixNano
	}
	return nil
}

// Provides additional context for a sample,
// such as thread ID or allocation size, with optional units. [deprecated]
type Label struct {
	unknownFields []byte
	Key           int64 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"` // Index into string table
	// At most one of the following must be present
	Str int64 `protobuf:"varint,2,opt,name=str,proto3" json:"str,omitempty"` // Index into string table
	Num int64 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	// Should only be present when num is present.
	// Specifies the units of num.
	// Use arbitrary string (for example, "requests") as a custom count unit.
	// If no unit is specified, consumer may apply heuristic to deduce the unit.
	// Consumers may also  interpret units like "bytes" and "kilobytes" as memory
	// units and units like "seconds" and "nanoseconds" as time units,
	// and apply appropriate unit conversions to these.
	NumUnit int64 `protobuf:"varint,4,opt,name=num_unit,json=numUnit,proto3" json:"numUnit,omitempty"` // Index into string table
}

func (x *Label) Reset() {
	*x = Label{}
}

func (*Label) ProtoMessage() {}

func (x *Label) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Label) GetStr() int64 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *Label) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Label) GetNumUnit() int64 {
	if x != nil {
		return x.NumUnit
	}
	return 0
}

// Describes the mapping of a binary in memory, including its address range,
// file offset, and metadata like build ID
type Mapping struct {
	unknownFields []byte
	// Unique nonzero id for the mapping. [deprecated]
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Address at which the binary (or DLL) is loaded into memory.
	MemoryStart uint64 `protobuf:"varint,2,opt,name=memory_start,json=memoryStart,proto3" json:"memoryStart,omitempty"`
	// The limit of the address range occupied by this mapping.
	MemoryLimit uint64 `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memoryLimit,omitempty"`
	// Offset in the binary that corresponds to the first mapped address.
	FileOffset uint64 `protobuf:"varint,4,opt,name=file_offset,json=fileOffset,proto3" json:"fileOffset,omitempty"`
	// The object this entry is loaded from.  This can be a filename on
	// disk for the main binary and shared libraries, or virtual
	// abstractions like "[vdso]".
	Filename int64 `protobuf:"varint,5,opt,name=filename,proto3" json:"filename,omitempty"` // Index into string table
	// A string that uniquely identifies a particular program version
	// with high probability. E.g., for binaries generated by GNU tools,
	// it could be the contents of the .note.gnu.build-id field.
	BuildId int64 `protobuf:"varint,6,opt,name=build_id,json=buildId,proto3" json:"buildId,omitempty"` // Index into string table
	// Specifies the kind of build id. See BuildIdKind enum for more details [optional]
	BuildIdKind BuildIdKind `protobuf:"varint,11,opt,name=build_id_kind,json=buildIdKind,proto3" json:"buildIdKind,omitempty"`
	// References to attributes in Profile.attribute_table. [optional]
	Attributes []uint64 `protobuf:"varint,12,rep,packed,name=attributes,proto3" json:"attributes,omitempty"`
	// The following fields indicate the resolution of symbolic info.
	HasFunctions    bool `protobuf:"varint,7,opt,name=has_functions,json=hasFunctions,proto3" json:"hasFunctions,omitempty"`
	HasFilenames    bool `protobuf:"varint,8,opt,name=has_filenames,json=hasFilenames,proto3" json:"hasFilenames,omitempty"`
	HasLineNumbers  bool `protobuf:"varint,9,opt,name=has_line_numbers,json=hasLineNumbers,proto3" json:"hasLineNumbers,omitempty"`
	HasInlineFrames bool `protobuf:"varint,10,opt,name=has_inline_frames,json=hasInlineFrames,proto3" json:"hasInlineFrames,omitempty"`
}

func (x *Mapping) Reset() {
	*x = Mapping{}
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mapping) GetMemoryStart() uint64 {
	if x != nil {
		return x.MemoryStart
	}
	return 0
}

func (x *Mapping) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Mapping) GetFileOffset() uint64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

func (x *Mapping) GetFilename() int64 {
	if x != nil {
		return x.Filename
	}
	return 0
}

func (x *Mapping) GetBuildId() int64 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *Mapping) GetBuildIdKind() BuildIdKind {
	if x != nil {
		return x.BuildIdKind
	}
	return BuildIdKind_BUILD_ID_LINKER
}

func (x *Mapping) GetAttributes() []uint64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Mapping) GetHasFunctions() bool {
	if x != nil {
		return x.HasFunctions
	}
	return false
}

func (x *Mapping) GetHasFilenames() bool {
	if x != nil {
		return x.HasFilenames
	}
	return false
}

func (x *Mapping) GetHasLineNumbers() bool {
	if x != nil {
		return x.HasLineNumbers
	}
	return false
}

func (x *Mapping) GetHasInlineFrames() bool {
	if x != nil {
		return x.HasInlineFrames
	}
	return false
}

// Describes function and line table debug information.
type Location struct {
	unknownFields []byte
	// Unique nonzero id for the location.  A profile could use
	// instruction addresses or any integer sequence as ids. [deprecated]
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The index of the corresponding profile.Mapping for this location.
	// It can be unset if the mapping is unknown or not applicable for
	// this profile type.
	MappingIndex uint64 `protobuf:"varint,2,opt,name=mapping_index,json=mappingIndex,proto3" json:"mappingIndex,omitempty"`
	// The instruction address for this location, if available.  It
	// should be within [Mapping.memory_start...Mapping.memory_limit]
	// for the corresponding mapping. A non-leaf address may be in the
	// middle of a call instruction. It is up to display tools to find
	// the beginning of the instruction if necessary.
	Address uint64 `protobuf:"varint,3,opt,name=address,proto3" json:"address,omitempty"`
	// Multiple line indicates this location has inlined functions,
	// where the last entry represents the caller into which the
	// preceding entries were inlined.
	//
	// E.g., if memcpy() is inlined into printf:
	//
	//	line[0].function_name == "memcpy"
	//	line[1].function_name == "printf"
	Line []*Line `protobuf:"bytes,4,rep,name=line,proto3" json:"line,omitempty"`
	// Provides an indication that multiple symbols map to this location's
	// address, for example due to identical code folding by the linker. In that
	// case the line information above represents one of the multiple
	// symbols. This field must be recomputed when the symbolization state of the
	// profile changes.
	IsFolded bool `protobuf:"varint,5,opt,name=is_folded,json=isFolded,proto3" json:"isFolded,omitempty"`
	// Type of frame (e.g. kernel, native, python, hotspot, php). Index into string table.
	TypeIndex uint32 `protobuf:"varint,6,opt,name=type_index,json=typeIndex,proto3" json:"typeIndex,omitempty"`
	// References to attributes in Profile.attribute_table. [optional]
	Attributes []uint64 `protobuf:"varint,7,rep,packed,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
}

func (*Location) ProtoMessage() {}

func (x *Location) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Location) GetMappingIndex() uint64 {
	if x != nil {
		return x.MappingIndex
	}
	return 0
}

func (x *Location) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Location) GetLine() []*Line {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *Location) GetIsFolded() bool {
	if x != nil {
		return x.IsFolded
	}
	return false
}

func (x *Location) GetTypeIndex() uint32 {
	if x != nil {
		return x.TypeIndex
	}
	return 0
}

func (x *Location) GetAttributes() []uint64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Details a specific line in a source code, linked to a function.
type Line struct {
	unknownFields []byte
	// The index of the corresponding profile.Function for this line.
	FunctionIndex uint64 `protobuf:"varint,1,opt,name=function_index,json=functionIndex,proto3" json:"functionIndex,omitempty"`
	// Line number in source code.
	Line int64 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	// Column number in source code.
	Column int64 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *Line) Reset() {
	*x = Line{}
}

func (*Line) ProtoMessage() {}

func (x *Line) GetFunctionIndex() uint64 {
	if x != nil {
		return x.FunctionIndex
	}
	return 0
}

func (x *Line) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Line) GetColumn() int64 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Describes a function, including its human-readable name, system name,
// source file, and starting line number in the source.
type Function struct {
	unknownFields []byte
	// Unique nonzero id for the function. [deprecated]
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the function, in human-readable form if available.
	Name int64 `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"` // Index into string table
	// Name of the function, as identified by the system.
	// For instance, it can be a C++ mangled name.
	SystemName int64 `protobuf:"varint,3,opt,name=system_name,json=systemName,proto3" json:"systemName,omitempty"` // Index into string table
	// Source file containing the function.
	Filename int64 `protobuf:"varint,4,opt,name=filename,proto3" json:"filename,omitempty"` // Index into string table
	// Line number in source file.
	StartLine int64 `protobuf:"varint,5,opt,name=start_line,json=startLine,proto3" json:"startLine,omitempty"`
}

func (x *Function) Reset() {
	*x = Function{}
}

func (*Function) ProtoMessage() {}

func (x *Function) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Function) GetName() int64 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Function) GetSystemName() int64 {
	if x != nil {
		return x.SystemName
	}
	return 0
}

func (x *Function) GetFilename() int64 {
	if x != nil {
		return x.Filename
	}
	return 0
}

func (x *Function) GetStartLine() int64 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

// MarshalProtoJSON marshals the AggregationTemporality to JSON.
func (x AggregationTemporality) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnumString(int32(x), AggregationTemporality_name)
}

// MarshalText marshals the AggregationTemporality to text.
func (x AggregationTemporality) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), AggregationTemporality_name)), nil
}

// MarshalJSON marshals the AggregationTemporality to JSON.
func (x AggregationTemporality) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the AggregationTemporality from JSON.
func (x *AggregationTemporality) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(AggregationTemporality_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read AggregationTemporality enum: %v", err)
		return
	}
	*x = AggregationTemporality(v)
}

// UnmarshalText unmarshals the AggregationTemporality from text.
func (x *AggregationTemporality) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), AggregationTemporality_value)
	if err != nil {
		return err
	}
	*x = AggregationTemporality(i)
	return nil
}

// UnmarshalJSON unmarshals the AggregationTemporality from JSON.
func (x *AggregationTemporality) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the BuildIdKind to JSON.
func (x BuildIdKind) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnumString(int32(x), BuildIdKind_name)
}

// MarshalText marshals the BuildIdKind to text.
func (x BuildIdKind) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), BuildIdKind_name)), nil
}

// MarshalJSON marshals the BuildIdKind to JSON.
func (x BuildIdKind) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the BuildIdKind from JSON.
func (x *BuildIdKind) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(BuildIdKind_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read BuildIdKind enum: %v", err)
		return
	}
	*x = BuildIdKind(v)
}

// UnmarshalText unmarshals the BuildIdKind from text.
func (x *BuildIdKind) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), BuildIdKind_value)
	if err != nil {
		return err
	}
	*x = BuildIdKind(i)
	return nil
}

// UnmarshalJSON unmarshals the BuildIdKind from JSON.
func (x *BuildIdKind) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Profile message to JSON.
func (x *Profile) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.SampleType) > 0 || s.HasField("sampleType") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sampleType")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.SampleType {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("sampleType"))
		}
		s.WriteArrayEnd()
	}
	if len(x.Sample) > 0 || s.HasField("sample") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("sample")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Sample {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("sample"))
		}
		s.WriteArrayEnd()
	}
	if len(x.Mapping) > 0 || s.HasField("mapping") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("mapping")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Mapping {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("mapping"))
		}
		s.WriteArrayEnd()
	}
	if len(x.Location) > 0 || s.HasField("location") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("location")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Location {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("location"))
		}
		s.WriteArrayEnd()
	}
	if len(x.LocationIndices) > 0 || s.HasField("locationIndices") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("locationIndices")
		s.WriteInt64Array(x.LocationIndices)
	}
	if len(x.Function) > 0 || s.HasField("function") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("function")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Function {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("function"))
		}
		s.WriteArrayEnd()
	}
	if len(x.AttributeTable) > 0 || s.HasField("attributeTable") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributeTable")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.AttributeTable {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("attributeTable"))
		}
		s.WriteArrayEnd()
	}
	if len(x.AttributeUnits) > 0 || s.HasField("attributeUnits") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributeUnits")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.AttributeUnits {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("attributeUnits"))
		}
		s.WriteArrayEnd()
	}
	if len(x.LinkTable) > 0 || s.HasField("linkTable") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("linkTable")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.LinkTable {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("linkTable"))
		}
		s.WriteArrayEnd()
	}
	if len(x.StringTable) > 0 || s.HasField("stringTable") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("stringTable")
		s.WriteStringArray(x.StringTable)
	}
	if x.DropFrames != 0 || s.HasField("dropFrames") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("dropFrames")
		s.WriteInt64(x.DropFrames)
	}
	if x.KeepFrames != 0 || s.HasField("keepFrames") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("keepFrames")
		s.WriteInt64(x.KeepFrames)
	}
	if x.TimeNanos != 0 || s.HasField("timeNanos") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timeNanos")
		s.WriteInt64(x.TimeNanos)
	}
	if x.DurationNanos != 0 || s.HasField("durationNanos") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("durationNanos")
		s.WriteInt64(x.DurationNanos)
	}
	if x.PeriodType != nil || s.HasField("periodType") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("periodType")
		x.PeriodType.MarshalProtoJSON(s.WithField("periodType"))
	}
	if x.Period != 0 || s.HasField("period") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("period")
		s.WriteInt64(x.Period)
	}
	if len(x.Comment) > 0 || s.HasField("comment") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("comment")
		s.WriteInt64Array(x.Comment)
	}
	if x.DefaultSampleType != 0 || s.HasField("defaultSampleType") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("defaultSampleType")
		s.WriteInt64(x.DefaultSampleType)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Profile to JSON.
func (x *Profile) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Profile message from JSON.
func (x *Profile) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "sample_type", "sampleType":
			s.AddField("sample_type")
			if s.ReadNil() {
				x.SampleType = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.SampleType = append(x.SampleType, nil)
					return
				}
				v := &ValueType{}
				v.UnmarshalProtoJSON(s.WithField("sample_type", false))
				if s.Err() != nil {
					return
				}
				x.SampleType = append(x.SampleType, v)
			})
		case "sample":
			s.AddField("sample")
			if s.ReadNil() {
				x.Sample = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Sample = append(x.Sample, nil)
					return
				}
				v := &Sample{}
				v.UnmarshalProtoJSON(s.WithField("sample", false))
				if s.Err() != nil {
					return
				}
				x.Sample = append(x.Sample, v)
			})
		case "mapping":
			s.AddField("mapping")
			if s.ReadNil() {
				x.Mapping = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Mapping = append(x.Mapping, nil)
					return
				}
				v := &Mapping{}
				v.UnmarshalProtoJSON(s.WithField("mapping", false))
				if s.Err() != nil {
					return
				}
				x.Mapping = append(x.Mapping, v)
			})
		case "location":
			s.AddField("location")
			if s.ReadNil() {
				x.Location = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Location = append(x.Location, nil)
					return
				}
				v := &Location{}
				v.UnmarshalProtoJSON(s.WithField("location", false))
				if s.Err() != nil {
					return
				}
				x.Location = append(x.Location, v)
			})
		case "location_indices", "locationIndices":
			s.AddField("location_indices")
			if s.ReadNil() {
				x.LocationIndices = nil
				return
			}
			x.LocationIndices = s.ReadInt64Array()
		case "function":
			s.AddField("function")
			if s.ReadNil() {
				x.Function = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Function = append(x.Function, nil)
					return
				}
				v := &Function{}
				v.UnmarshalProtoJSON(s.WithField("function", false))
				if s.Err() != nil {
					return
				}
				x.Function = append(x.Function, v)
			})
		case "attribute_table", "attributeTable":
			s.AddField("attribute_table")
			if s.ReadNil() {
				x.AttributeTable = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.AttributeTable = append(x.AttributeTable, nil)
					return
				}
				v := &v1.KeyValue{}
				v.UnmarshalProtoJSON(s.WithField("attribute_table", false))
				if s.Err() != nil {
					return
				}
				x.AttributeTable = append(x.AttributeTable, v)
			})
		case "attribute_units", "attributeUnits":
			s.AddField("attribute_units")
			if s.ReadNil() {
				x.AttributeUnits = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.AttributeUnits = append(x.AttributeUnits, nil)
					return
				}
				v := &AttributeUnit{}
				v.UnmarshalProtoJSON(s.WithField("attribute_units", false))
				if s.Err() != nil {
					return
				}
				x.AttributeUnits = append(x.AttributeUnits, v)
			})
		case "link_table", "linkTable":
			s.AddField("link_table")
			if s.ReadNil() {
				x.LinkTable = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.LinkTable = append(x.LinkTable, nil)
					return
				}
				v := &Link{}
				v.UnmarshalProtoJSON(s.WithField("link_table", false))
				if s.Err() != nil {
					return
				}
				x.LinkTable = append(x.LinkTable, v)
			})
		case "string_table", "stringTable":
			s.AddField("string_table")
			if s.ReadNil() {
				x.StringTable = nil
				return
			}
			x.StringTable = s.ReadStringArray()
		case "drop_frames", "dropFrames":
			s.AddField("drop_frames")
			x.DropFrames = s.ReadInt64()
		case "keep_frames", "keepFrames":
			s.AddField("keep_frames")
			x.KeepFrames = s.ReadInt64()
		case "time_nanos", "timeNanos":
			s.AddField("time_nanos")
			x.TimeNanos = s.ReadInt64()
		case "duration_nanos", "durationNanos":
			s.AddField("duration_nanos")
			x.DurationNanos = s.ReadInt64()
		case "period_type", "periodType":
			if s.ReadNil() {
				x.PeriodType = nil
				return
			}
			x.PeriodType = &ValueType{}
			x.PeriodType.UnmarshalProtoJSON(s.WithField("period_type", true))
		case "period":
			s.AddField("period")
			x.Period = s.ReadInt64()
		case "comment":
			s.AddField("comment")
			if s.ReadNil() {
				x.Comment = nil
				return
			}
			x.Comment = s.ReadInt64Array()
		case "default_sample_type", "defaultSampleType":
			s.AddField("default_sample_type")
			x.DefaultSampleType = s.ReadInt64()
		}
	})
}

// UnmarshalJSON unmarshals the Profile from JSON.
func (x *Profile) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the AttributeUnit message to JSON.
func (x *AttributeUnit) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.AttributeKey != 0 || s.HasField("attributeKey") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributeKey")
		s.WriteInt64(x.AttributeKey)
	}
	if x.Unit != 0 || s.HasField("unit") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("unit")
		s.WriteInt64(x.Unit)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the AttributeUnit to JSON.
func (x *AttributeUnit) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the AttributeUnit message from JSON.
func (x *AttributeUnit) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "attribute_key", "attributeKey":
			s.AddField("attribute_key")
			x.AttributeKey = s.ReadInt64()
		case "unit":
			s.AddField("unit")
			x.Unit = s.ReadInt64()
		}
	})
}

// UnmarshalJSON unmarshals the AttributeUnit from JSON.
func (x *AttributeUnit) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Link message to JSON.
func (x *Link) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.TraceId) > 0 || s.HasField("traceId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("traceId")
		s.WriteBytes(x.TraceId)
	}
	if len(x.SpanId) > 0 || s.HasField("spanId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("spanId")
		s.WriteBytes(x.SpanId)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Link to JSON.
func (x *Link) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Link message from JSON.
func (x *Link) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "trace_id", "traceId":
			s.AddField("trace_id")
			x.TraceId = s.ReadBytes()
		case "span_id", "spanId":
			s.AddField("span_id")
			x.SpanId = s.ReadBytes()
		}
	})
}

// UnmarshalJSON unmarshals the Link from JSON.
func (x *Link) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ValueType message to JSON.
func (x *ValueType) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Type != 0 || s.HasField("type") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("type")
		s.WriteInt64(x.Type)
	}
	if x.Unit != 0 || s.HasField("unit") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("unit")
		s.WriteInt64(x.Unit)
	}
	if x.AggregationTemporality != 0 || s.HasField("aggregationTemporality") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("aggregationTemporality")
		x.AggregationTemporality.MarshalProtoJSON(s)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ValueType to JSON.
func (x *ValueType) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ValueType message from JSON.
func (x *ValueType) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "type":
			s.AddField("type")
			x.Type = s.ReadInt64()
		case "unit":
			s.AddField("unit")
			x.Unit = s.ReadInt64()
		case "aggregation_temporality", "aggregationTemporality":
			s.AddField("aggregation_temporality")
			x.AggregationTemporality.UnmarshalProtoJSON(s)
		}
	})
}

// UnmarshalJSON unmarshals the ValueType from JSON.
func (x *ValueType) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Sample message to JSON.
func (x *Sample) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.LocationIndex) > 0 || s.HasField("locationIndex") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("locationIndex")
		s.WriteUint64Array(x.LocationIndex)
	}
	if x.LocationsStartIndex != 0 || s.HasField("locationsStartIndex") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("locationsStartIndex")
		s.WriteUint64(x.LocationsStartIndex)
	}
	if x.LocationsLength != 0 || s.HasField("locationsLength") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("locationsLength")
		s.WriteUint64(x.LocationsLength)
	}
	if x.StacktraceIdIndex != 0 || s.HasField("stacktraceIdIndex") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("stacktraceIdIndex")
		s.WriteUint32(x.StacktraceIdIndex)
	}
	if len(x.Value) > 0 || s.HasField("value") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("value")
		s.WriteInt64Array(x.Value)
	}
	if len(x.Label) > 0 || s.HasField("label") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("label")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Label {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("label"))
		}
		s.WriteArrayEnd()
	}
	if len(x.Attributes) > 0 || s.HasField("attributes") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributes")
		s.WriteUint64Array(x.Attributes)
	}
	if x.Link != 0 || s.HasField("link") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("link")
		s.WriteUint64(x.Link)
	}
	if len(x.TimestampsUnixNano) > 0 || s.HasField("timestampsUnixNano") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("timestampsUnixNano")
		s.WriteUint64Array(x.TimestampsUnixNano)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Sample to JSON.
func (x *Sample) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Sample message from JSON.
func (x *Sample) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "location_index", "locationIndex":
			s.AddField("location_index")
			if s.ReadNil() {
				x.LocationIndex = nil
				return
			}
			x.LocationIndex = s.ReadUint64Array()
		case "locations_start_index", "locationsStartIndex":
			s.AddField("locations_start_index")
			x.LocationsStartIndex = s.ReadUint64()
		case "locations_length", "locationsLength":
			s.AddField("locations_length")
			x.LocationsLength = s.ReadUint64()
		case "stacktrace_id_index", "stacktraceIdIndex":
			s.AddField("stacktrace_id_index")
			x.StacktraceIdIndex = s.ReadUint32()
		case "value":
			s.AddField("value")
			if s.ReadNil() {
				x.Value = nil
				return
			}
			x.Value = s.ReadInt64Array()
		case "label":
			s.AddField("label")
			if s.ReadNil() {
				x.Label = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Label = append(x.Label, nil)
					return
				}
				v := &Label{}
				v.UnmarshalProtoJSON(s.WithField("label", false))
				if s.Err() != nil {
					return
				}
				x.Label = append(x.Label, v)
			})
		case "attributes":
			s.AddField("attributes")
			if s.ReadNil() {
				x.Attributes = nil
				return
			}
			x.Attributes = s.ReadUint64Array()
		case "link":
			s.AddField("link")
			x.Link = s.ReadUint64()
		case "timestamps_unix_nano", "timestampsUnixNano":
			s.AddField("timestamps_unix_nano")
			if s.ReadNil() {
				x.TimestampsUnixNano = nil
				return
			}
			x.TimestampsUnixNano = s.ReadUint64Array()
		}
	})
}

// UnmarshalJSON unmarshals the Sample from JSON.
func (x *Sample) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Label message to JSON.
func (x *Label) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Key != 0 || s.HasField("key") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("key")
		s.WriteInt64(x.Key)
	}
	if x.Str != 0 || s.HasField("str") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("str")
		s.WriteInt64(x.Str)
	}
	if x.Num != 0 || s.HasField("num") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("num")
		s.WriteInt64(x.Num)
	}
	if x.NumUnit != 0 || s.HasField("numUnit") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("numUnit")
		s.WriteInt64(x.NumUnit)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Label to JSON.
func (x *Label) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Label message from JSON.
func (x *Label) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "key":
			s.AddField("key")
			x.Key = s.ReadInt64()
		case "str":
			s.AddField("str")
			x.Str = s.ReadInt64()
		case "num":
			s.AddField("num")
			x.Num = s.ReadInt64()
		case "num_unit", "numUnit":
			s.AddField("num_unit")
			x.NumUnit = s.ReadInt64()
		}
	})
}

// UnmarshalJSON unmarshals the Label from JSON.
func (x *Label) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Mapping message to JSON.
func (x *Mapping) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Id != 0 || s.HasField("id") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("id")
		s.WriteUint64(x.Id)
	}
	if x.MemoryStart != 0 || s.HasField("memoryStart") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("memoryStart")
		s.WriteUint64(x.MemoryStart)
	}
	if x.MemoryLimit != 0 || s.HasField("memoryLimit") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("memoryLimit")
		s.WriteUint64(x.MemoryLimit)
	}
	if x.FileOffset != 0 || s.HasField("fileOffset") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("fileOffset")
		s.WriteUint64(x.FileOffset)
	}
	if x.Filename != 0 || s.HasField("filename") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("filename")
		s.WriteInt64(x.Filename)
	}
	if x.BuildId != 0 || s.HasField("buildId") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("buildId")
		s.WriteInt64(x.BuildId)
	}
	if x.BuildIdKind != 0 || s.HasField("buildIdKind") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("buildIdKind")
		x.BuildIdKind.MarshalProtoJSON(s)
	}
	if len(x.Attributes) > 0 || s.HasField("attributes") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributes")
		s.WriteUint64Array(x.Attributes)
	}
	if x.HasFunctions || s.HasField("hasFunctions") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("hasFunctions")
		s.WriteBool(x.HasFunctions)
	}
	if x.HasFilenames || s.HasField("hasFilenames") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("hasFilenames")
		s.WriteBool(x.HasFilenames)
	}
	if x.HasLineNumbers || s.HasField("hasLineNumbers") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("hasLineNumbers")
		s.WriteBool(x.HasLineNumbers)
	}
	if x.HasInlineFrames || s.HasField("hasInlineFrames") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("hasInlineFrames")
		s.WriteBool(x.HasInlineFrames)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Mapping to JSON.
func (x *Mapping) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Mapping message from JSON.
func (x *Mapping) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "id":
			s.AddField("id")
			x.Id = s.ReadUint64()
		case "memory_start", "memoryStart":
			s.AddField("memory_start")
			x.MemoryStart = s.ReadUint64()
		case "memory_limit", "memoryLimit":
			s.AddField("memory_limit")
			x.MemoryLimit = s.ReadUint64()
		case "file_offset", "fileOffset":
			s.AddField("file_offset")
			x.FileOffset = s.ReadUint64()
		case "filename":
			s.AddField("filename")
			x.Filename = s.ReadInt64()
		case "build_id", "buildId":
			s.AddField("build_id")
			x.BuildId = s.ReadInt64()
		case "build_id_kind", "buildIdKind":
			s.AddField("build_id_kind")
			x.BuildIdKind.UnmarshalProtoJSON(s)
		case "attributes":
			s.AddField("attributes")
			if s.ReadNil() {
				x.Attributes = nil
				return
			}
			x.Attributes = s.ReadUint64Array()
		case "has_functions", "hasFunctions":
			s.AddField("has_functions")
			x.HasFunctions = s.ReadBool()
		case "has_filenames", "hasFilenames":
			s.AddField("has_filenames")
			x.HasFilenames = s.ReadBool()
		case "has_line_numbers", "hasLineNumbers":
			s.AddField("has_line_numbers")
			x.HasLineNumbers = s.ReadBool()
		case "has_inline_frames", "hasInlineFrames":
			s.AddField("has_inline_frames")
			x.HasInlineFrames = s.ReadBool()
		}
	})
}

// UnmarshalJSON unmarshals the Mapping from JSON.
func (x *Mapping) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Location message to JSON.
func (x *Location) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Id != 0 || s.HasField("id") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("id")
		s.WriteUint64(x.Id)
	}
	if x.MappingIndex != 0 || s.HasField("mappingIndex") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("mappingIndex")
		s.WriteUint64(x.MappingIndex)
	}
	if x.Address != 0 || s.HasField("address") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("address")
		s.WriteUint64(x.Address)
	}
	if len(x.Line) > 0 || s.HasField("line") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("line")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.Line {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("line"))
		}
		s.WriteArrayEnd()
	}
	if x.IsFolded || s.HasField("isFolded") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("isFolded")
		s.WriteBool(x.IsFolded)
	}
	if x.TypeIndex != 0 || s.HasField("typeIndex") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("typeIndex")
		s.WriteUint32(x.TypeIndex)
	}
	if len(x.Attributes) > 0 || s.HasField("attributes") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("attributes")
		s.WriteUint64Array(x.Attributes)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Location to JSON.
func (x *Location) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Location message from JSON.
func (x *Location) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "id":
			s.AddField("id")
			x.Id = s.ReadUint64()
		case "mapping_index", "mappingIndex":
			s.AddField("mapping_index")
			x.MappingIndex = s.ReadUint64()
		case "address":
			s.AddField("address")
			x.Address = s.ReadUint64()
		case "line":
			s.AddField("line")
			if s.ReadNil() {
				x.Line = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.Line = append(x.Line, nil)
					return
				}
				v := &Line{}
				v.UnmarshalProtoJSON(s.WithField("line", false))
				if s.Err() != nil {
					return
				}
				x.Line = append(x.Line, v)
			})
		case "is_folded", "isFolded":
			s.AddField("is_folded")
			x.IsFolded = s.ReadBool()
		case "type_index", "typeIndex":
			s.AddField("type_index")
			x.TypeIndex = s.ReadUint32()
		case "attributes":
			s.AddField("attributes")
			if s.ReadNil() {
				x.Attributes = nil
				return
			}
			x.Attributes = s.ReadUint64Array()
		}
	})
}

// UnmarshalJSON unmarshals the Location from JSON.
func (x *Location) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Line message to JSON.
func (x *Line) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.FunctionIndex != 0 || s.HasField("functionIndex") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("functionIndex")
		s.WriteUint64(x.FunctionIndex)
	}
	if x.Line != 0 || s.HasField("line") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("line")
		s.WriteInt64(x.Line)
	}
	if x.Column != 0 || s.HasField("column") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("column")
		s.WriteInt64(x.Column)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Line to JSON.
func (x *Line) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Line message from JSON.
func (x *Line) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "function_index", "functionIndex":
			s.AddField("function_index")
			x.FunctionIndex = s.ReadUint64()
		case "line":
			s.AddField("line")
			x.Line = s.ReadInt64()
		case "column":
			s.AddField("column")
			x.Column = s.ReadInt64()
		}
	})
}

// UnmarshalJSON unmarshals the Line from JSON.
func (x *Line) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the Function message to JSON.
func (x *Function) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Id != 0 || s.HasField("id") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("id")
		s.WriteUint64(x.Id)
	}
	if x.Name != 0 || s.HasField("name") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("name")
		s.WriteInt64(x.Name)
	}
	if x.SystemName != 0 || s.HasField("systemName") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("systemName")
		s.WriteInt64(x.SystemName)
	}
	if x.Filename != 0 || s.HasField("filename") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("filename")
		s.WriteInt64(x.Filename)
	}
	if x.StartLine != 0 || s.HasField("startLine") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("startLine")
		s.WriteInt64(x.StartLine)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the Function to JSON.
func (x *Function) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the Function message from JSON.
func (x *Function) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "id":
			s.AddField("id")
			x.Id = s.ReadUint64()
		case "name":
			s.AddField("name")
			x.Name = s.ReadInt64()
		case "system_name", "systemName":
			s.AddField("system_name")
			x.SystemName = s.ReadInt64()
		case "filename":
			s.AddField("filename")
			x.Filename = s.ReadInt64()
		case "start_line", "startLine":
			s.AddField("start_line")
			x.StartLine = s.ReadInt64()
		}
	})
}

// UnmarshalJSON unmarshals the Function from JSON.
func (x *Function) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}
