// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: (devel)
// source: opentelemetry/proto/collector/logs/v1/logs_service.proto

package opentelemetry_proto_collector_logs_v1

import (
	json "github.com/aperturerobotics/protobuf-go-lite/json"
	v1 "go.opentelemetry.io/proto/lite/otlp/logs/v1"
)

// Copyright 2020, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

type ExportLogsServiceRequest struct {
	unknownFields []byte
	// An array of ResourceLogs.
	// For data coming from a single resource this array will typically contain one
	// element. Intermediary nodes (such as OpenTelemetry Collector) that receive
	// data from multiple origins typically batch the data before forwarding further and
	// in that case this array will contain multiple elements.
	ResourceLogs []*v1.ResourceLogs `protobuf:"bytes,1,rep,name=resource_logs,json=resourceLogs,proto3" json:"resourceLogs,omitempty"`
}

func (x *ExportLogsServiceRequest) Reset() {
	*x = ExportLogsServiceRequest{}
}

func (*ExportLogsServiceRequest) ProtoMessage() {}

func (x *ExportLogsServiceRequest) GetResourceLogs() []*v1.ResourceLogs {
	if x != nil {
		return x.ResourceLogs
	}
	return nil
}

type ExportLogsServiceResponse struct {
	unknownFields []byte
	// The details of a partially successful export request.
	//
	// If the request is only partially accepted
	// (i.e. when the server accepts only parts of the data and rejects the rest)
	// the server MUST initialize the `partial_success` field and MUST
	// set the `rejected_<signal>` with the number of items it rejected.
	//
	// Servers MAY also make use of the `partial_success` field to convey
	// warnings/suggestions to senders even when the request was fully accepted.
	// In such cases, the `rejected_<signal>` MUST have a value of `0` and
	// the `error_message` MUST be non-empty.
	//
	// A `partial_success` message with an empty value (rejected_<signal> = 0 and
	// `error_message` = "") is equivalent to it not being set/present. Senders
	// SHOULD interpret it the same way as in the full success case.
	PartialSuccess *ExportLogsPartialSuccess `protobuf:"bytes,1,opt,name=partial_success,json=partialSuccess,proto3" json:"partialSuccess,omitempty"`
}

func (x *ExportLogsServiceResponse) Reset() {
	*x = ExportLogsServiceResponse{}
}

func (*ExportLogsServiceResponse) ProtoMessage() {}

func (x *ExportLogsServiceResponse) GetPartialSuccess() *ExportLogsPartialSuccess {
	if x != nil {
		return x.PartialSuccess
	}
	return nil
}

type ExportLogsPartialSuccess struct {
	unknownFields []byte
	// The number of rejected log records.
	//
	// A `rejected_<signal>` field holding a `0` value indicates that the
	// request was fully accepted.
	RejectedLogRecords int64 `protobuf:"varint,1,opt,name=rejected_log_records,json=rejectedLogRecords,proto3" json:"rejectedLogRecords,omitempty"`
	// A developer-facing human-readable message in English. It should be used
	// either to explain why the server rejected parts of the data during a partial
	// success or to convey warnings/suggestions during a full success. The message
	// should offer guidance on how users can address such issues.
	//
	// error_message is an optional field. An error_message with an empty value
	// is equivalent to it not being set.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *ExportLogsPartialSuccess) Reset() {
	*x = ExportLogsPartialSuccess{}
}

func (*ExportLogsPartialSuccess) ProtoMessage() {}

func (x *ExportLogsPartialSuccess) GetRejectedLogRecords() int64 {
	if x != nil {
		return x.RejectedLogRecords
	}
	return 0
}

func (x *ExportLogsPartialSuccess) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// MarshalProtoJSON marshals the ExportLogsServiceRequest message to JSON.
func (x *ExportLogsServiceRequest) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if len(x.ResourceLogs) > 0 || s.HasField("resourceLogs") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("resourceLogs")
		s.WriteArrayStart()
		var wroteElement bool
		for _, element := range x.ResourceLogs {
			s.WriteMoreIf(&wroteElement)
			element.MarshalProtoJSON(s.WithField("resourceLogs"))
		}
		s.WriteArrayEnd()
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ExportLogsServiceRequest to JSON.
func (x *ExportLogsServiceRequest) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ExportLogsServiceRequest message from JSON.
func (x *ExportLogsServiceRequest) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "resource_logs", "resourceLogs":
			s.AddField("resource_logs")
			if s.ReadNil() {
				x.ResourceLogs = nil
				return
			}
			s.ReadArray(func() {
				if s.ReadNil() {
					x.ResourceLogs = append(x.ResourceLogs, nil)
					return
				}
				v := &v1.ResourceLogs{}
				v.UnmarshalProtoJSON(s.WithField("resource_logs", false))
				if s.Err() != nil {
					return
				}
				x.ResourceLogs = append(x.ResourceLogs, v)
			})
		}
	})
}

// UnmarshalJSON unmarshals the ExportLogsServiceRequest from JSON.
func (x *ExportLogsServiceRequest) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ExportLogsServiceResponse message to JSON.
func (x *ExportLogsServiceResponse) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.PartialSuccess != nil || s.HasField("partialSuccess") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("partialSuccess")
		x.PartialSuccess.MarshalProtoJSON(s.WithField("partialSuccess"))
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ExportLogsServiceResponse to JSON.
func (x *ExportLogsServiceResponse) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ExportLogsServiceResponse message from JSON.
func (x *ExportLogsServiceResponse) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "partial_success", "partialSuccess":
			if s.ReadNil() {
				x.PartialSuccess = nil
				return
			}
			x.PartialSuccess = &ExportLogsPartialSuccess{}
			x.PartialSuccess.UnmarshalProtoJSON(s.WithField("partial_success", true))
		}
	})
}

// UnmarshalJSON unmarshals the ExportLogsServiceResponse from JSON.
func (x *ExportLogsServiceResponse) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the ExportLogsPartialSuccess message to JSON.
func (x *ExportLogsPartialSuccess) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.RejectedLogRecords != 0 || s.HasField("rejectedLogRecords") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("rejectedLogRecords")
		s.WriteInt64(x.RejectedLogRecords)
	}
	if x.ErrorMessage != "" || s.HasField("errorMessage") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("errorMessage")
		s.WriteString(x.ErrorMessage)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the ExportLogsPartialSuccess to JSON.
func (x *ExportLogsPartialSuccess) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ExportLogsPartialSuccess message from JSON.
func (x *ExportLogsPartialSuccess) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "rejected_log_records", "rejectedLogRecords":
			s.AddField("rejected_log_records")
			x.RejectedLogRecords = s.ReadInt64()
		case "error_message", "errorMessage":
			s.AddField("error_message")
			x.ErrorMessage = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the ExportLogsPartialSuccess from JSON.
func (x *ExportLogsPartialSuccess) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}
